administrador/urls.py
# administrador/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),  
    path('gerenciamento/', views.gerenciamento_view, name='gerenciamento'),
]

candidato/urls.py
from django.urls import path
from . import views

app_name = 'candidato'

urlpatterns = [
    path('tela_principal_candidato/', views.tela_principal_candidato, name='tela_principal_candidato'), 
    
    path('perfil/', views.perfil_candidato, name='perfil_candidato'),
    
    path('candidaturas/', views.candidaturas_candidato, name='candidaturas_candidato'),
    
    path('vagas/', views.vagas_candidato, name='vagas_candidato'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='base'),
]

empresa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='base'),
]

workconnect/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('empresa/', include('empresa.urls')),
    path('candidato/', include('candidato.urls')),
    path('administrador/', include('administrador.urls')),
    ]

administrador/models.py
from django.db import models

# Create your models here.

administrador/views.py
from django.shortcuts import render

def dashboard(request):
    return render(request, 'administrador/dashboard.html')

def gerenciamento_view(request):
    return render(request, 'administrador/gerenciamento.html')

candidato/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'candidato/base.html')

def tela_principal_candidato(request):
    return render(request, 'candidato/tela_principal_candidato.html')

def perfil_candidato(request):
    return render(request, 'candidato/perfil.html') 

def candidaturas_candidato(request):
    return render(request, 'candidato/candidaturas.html')

def vagas_candidato(request):
    return render(request, 'candidato/vagas.html')

core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/base.html')

empresa/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'empresa/base.html')

administrador/templates/administrador/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dashboard - Administrador</title>
  <link rel="stylesheet" href="{% static 'administrador/css/dashboard.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
</head>
<body>
  <main class="dashboard">
    <section class="boas-vindas">
      <h1>Bem vindo de volta, <span>Admin!</span></h1>
      <p>Aqui estão as últimas atualizações do sistema.</p>
    </section>

    <section class="metricas">
      <div class="card">
        <div class="icon">
          <i class="fa-solid fa-user-group"></i>
        </div>
        <div class="info">
          <p>Candidatos Cadastrados</p>
          <h3>5,423</h3>
        </div>
      </div>

      <div class="card">
        <div class="icon">
          <i class="fa-solid fa-building-user"></i>
        </div>
        <div class="info">
          <p>Empresas Cadastradas</p>
          <h3>1,893</h3>
        </div>
      </div>

      <div class="card">
        <div class="icon">
          <i class="fa-solid fa-desktop"></i>
        </div>
        <div class="info">
          <p>Vagas Publicadas</p>
          <h3>189</h3>
        </div>
      </div>

      <div class="card">
        <div class="icon">
          <i class="fa-solid fa-user-check"></i>
        </div>
        <div class="info">
          <p>Vagas Ativas</p>
          <h3>5,423</h3>
        </div>
      </div>
    </section>

    <h2 class="titulo-gerenciamento">Gerenciamento</h2>

    <section class="painel-gerenciamento">
      <div class="bloco">
        <div class="texto">
          <h3>Candidatos</h3>
          <p>Visualizar, editar e gerenciar perfis de candidatos</p>
          <button>10 registros</button>
        </div>
        <i class="fa-solid fa-user"></i>
      </div>

      <div class="bloco">
        <div class="texto">
          <h3>Empresas</h3>
          <p>Visualizar, editar e gerenciar empresas cadastradas</p>
          <button>10 registros</button>
        </div>
        <i class="fa-solid fa-building"></i>
      </div>

      <div class="bloco">
        <div class="texto">
          <h3>Vagas</h3>
          <p>Visualizar, editar e gerenciar vagas publicadas</p>
          <button>10 registros</button>
        </div>
        <i class="fa-solid fa-briefcase"></i>
      </div>
    </section>
  </main>
</body>
</html>

administrador/templates/administrador/gerenciamento.html
{% load static %}

<html lang="pt-br">
<head>
    <title>Gerenciamento</title>
  <link rel="stylesheet" href="{% static 'administrador/css/gerenciamento.css' %}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    
 <header class="navbar">
    <div class="container">
      <img src="{% static 'core/img/LogoTemplate.png' %}" alt="WorkConnect" class="logo">
      <nav>
        <a href="#">Plataforma</a>
        <a href="#">Serviços</a>
        <a href="#">Suporte</a>
      </nav>
      <div class="user-icon">
         <i class="fa-solid fa-bell"></i>
      </div>
    </div>
  </header>

  <div class="search-container">
  <div class="search-bar">
    <div class="search-item">
      <i class="fa fa-search"></i>
      <input type="text" placeholder="Pesquisar por nome">
    </div>
    <div class="divider"></div>
    <div class="search-item">
      <i class="fa fa-map-marker-alt"></i>
      <input type="text" placeholder="|E-mail">
    </div>
    <div class="divider"></div>
    <div class="search-item">
      <i class="fa fa-layer-group"></i>
      <select>
        <option selected disabled>Selecionar por Status</option>
        <option>Ativo</option>
        <option>Inativo</option>
      </select>
    </div>
    <button class="search-btn">Buscar</button>
  </div>
</div>

  <div class="container">
    <div class="tabela-container">
      <table class="tabela-usuarios">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Tipo</th>
            <th>Status</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="perfil">
             <img src="{% static 'administrador/img/Cristiano.png' %}">
              Cristiano Ronaldo
            </td>
            <td>cristiano@example.com</td>
            <td>Empresa</td>
            <td><span class="status inativo">● Inativo</span></td>
            <td>
              <button class="excluir">Excluir</button>
              <button class="detalhes">↗</button>
            </td>
          </tr>

          <tr>
            <td class="perfil">
                    <img src="{% static 'administrador/img/Nubank.png' %}">
              Nubank
            </td>
            <td>nubank@gmail.com</td>
            <td>Candidato</td>
            <td><span class="status ativo">● Ativo</span></td>
            <td>
              <button class="excluir">Excluir</button>
              <button class="detalhes">↗</button>
            </td>
          </tr>

          <tr>
            <td class="perfil">
    <img src="{% static 'administrador/img/Alan.png' %}">
                  Alan Costa
            </td>
            <td>alan@gmail.com</td>
            <td>Candidato</td>
            <td><span class="status inativo">● Inativo</span></td>
            <td>
              <button class="excluir">Excluir</button>
              <button class="detalhes">↗</button>
            </td>
          </tr>

          <tr>
            <td class="perfil">
    <img src="{% static 'administrador/img/Eletrica.png' %}">
                  Cervejaria Elétrica
            </td>
            <td>eletrica@gmail.com</td>
            <td>Empresa</td>
            <td><span class="status ativo">● Ativo</span></td>
            <td>
              <button class="excluir">Excluir</button>
              <button class="detalhes">↗</button>
            </td>
          </tr>

          <tr>
            <td class="perfil">
    <img src="{% static 'administrador/img/Arrascaeta.png' %}">
                  Giorgian De Arrascaeta
            </td>
            <td>arrascaeta@gmail.com</td>
            <td>Candidato</td>
            <td><span class="status inativo">● Inativo</span></td>
            <td>
              <button class="excluir">Excluir</button>
              <button class="detalhes">↗</button>
            </td>
          </tr>

          <tr>
            <td class="perfil">
    <img src="{% static 'administrador/img/Brisanet.png' %}">
                  Brisanet
            </td>
            <td>brisanet@gmail.com</td>
            <td>Empresa</td>
            <td><span class="status ativo">● Ativo</span></td>
            <td>
              <button class="excluir">Excluir</button>
              <button class="detalhes">↗</button>
            </td>
          </tr>

          <tr>
            <td class="perfil">
    <img src="{% static 'administrador/img/Thiago.png' %}">
                  Thiago Henrique
            </td>
            <td>thiago@gmail.com</td>
            <td>Candidato</td>
            <td><span class="status inativo">● Inativo</span></td>
            <td>
              <button class="excluir">Excluir</button>
              <button class="detalhes">↗</button>
            </td>
          </tr>

          <tr>
            <td class="perfil">
    <img src="{% static 'administrador/img/Nike.png' %}">
                  Nike
            </td>
            <td>nike@gmail.com</td>
            <td>Empresa</td>
            <td><span class="status ativo">● Ativo</span></td>
            <td>
              <button class="excluir">Excluir</button>
              <button class="detalhes">↗</button>
            </td>
          </tr>

          <tr>
            <td class="perfil">
    <img src="{% static 'administrador/img/Irlan.png' %}">
                  Irlan
            </td>
            <td>irlan@gmail.com</td>
            <td>Empresa</td>
            <td><span class="status inativo">● Inativo</span></td>
            <td>
              <button class="excluir">Excluir</button>
              <button class="detalhes">↗</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

</body>
</html>

candidato/templates/candidato/candidaturas.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}WorkConnect | Candidaturas{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'core/css/candidaturas_candidato.css' %}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
</head>
<body>

  <header class="navbar">
    <div class="container">
      <img src="{% static 'core/img/LogoTemplate.png' %}" alt="WorkConnect" class="logo">
      <nav>
        <a href="#">Plataforma</a>
        <a href="#">Serviços</a>
        <a href="#">Suporte</a>
      </nav>
      <div class="user-icon">
        <i class="fa-solid fa-circle-user"></i>
      </div>
    </div>
  </header>

  <section class="filter-section">
  <h2 class="filter-title">Filtros</h2>

  <div class="search-bar">
          <input type="text" placeholder="Cargo, Empresas..." class="input-job">
          <input type="text" placeholder="Cidade" class="input-location">
          <input type="text" placeholder="Modo de trabalho" class="input-location">
          <button>Buscar Vaga</button>
        </div>
      </div>
  
<section class="vagas-section">
  <h2 class="candidaturas-title">Suas Candidaturas:</h2>

  <div class="cards-container">

  <div class="card">
    <div class="card-header">
      <img src="{% static 'core/img/Ellipse 14.png' %}">
    </div>
    <div class="card-body">
      <p class="company-name">Elétrica Cervejaria <span class="status">Ativa</span></p>
      <p class="company-location">Pau dos Ferros/RN</p>

      <div class="info-label"><span>🎯 Vaga</span></div>
      <div class="info-value">Barmen</div>

      <div class="info-label"><span>⏰ Turno e Horário</span></div>
      <div class="info-value">Noturno - 4h</div>

      <a href="#" class="details-button">Detalhes ›</a>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <img src="{% static 'core/img/Farmacia.png' %}">
    </div>
    <div class="card-body">
      <p class="company-name">Farmacia Ideal <span class="status">Ativa</span></p>
      <p class="company-location">Pau dos Ferros/RN</p>
      <div class="info-label"><span>🎯 Vaga</span></div>
      <div class="info-value">Farmacêutico</div>
      <div class="info-label"><span>⏰ Turno e Horário</span></div>
      <div class="info-value">Integral - 10h</div>
      <a href="#" class="details-button">Detalhes ›</a>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <img src="{% static 'core/img/Hotel.png' %}">
    </div>
    <div class="card-body">
      <p class="company-name">West Hotel <span class="status">Ativa</span></p>
      <p class="company-location">Pau dos Ferros/RN</p>
      <div class="info-label"><span>🎯 Vaga</span></div>
      <div class="info-value">Camareiro (a)</div>
      <div class="info-label"><span>⏰ Turno e Horário</span></div>
      <div class="info-value">Meio périodo - 6h</div>
      <a href="#" class="details-button">Detalhes ›</a>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <img src="{% static 'core/img/Peechinchou.png' %}">
    </div>
    <div class="card-body">
      <p class="company-name">Pechinchou <span class="status">Ativa</span></p>
      <p class="company-location">Pau dos Ferros/RN</p>

      <div class="info-label"><span>🎯 Vaga</span></div>
      <div class="info-value">Social Media</div>

      <div class="info-label"><span>⏰ Turno e Horário</span></div>
      <div class="info-value">Fléxivel - 8h</div>

      <a href="#" class="details-button">Detalhes ›</a>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <img src="{% static 'core/img/Atacarejo.png' %}">
    </div>
    <div class="card-body">
      <p class="company-name">Nosso Atacarejo <span class="status">Ativa</span></p>
      <p class="company-location">Pau dos Ferros/RN</p>

      <div class="info-label"><span>🎯 Vaga</span></div>
      <div class="info-value">Operador(a) de caixa</div>

      <div class="info-label"><span>⏰ Turno e Horário</span></div>
      <div class="info-value">Integral - 8h</div>

      <a href="#" class="details-button">Detalhes ›</a>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <img src="{% static 'core/img/Pizzaria.png' %}">
    </div>
    <div class="card-body">
      <p class="company-name">Água na boca<span class="status">Ativa</span></p>
      <p class="company-location">Pau dos Ferros/RN</p>

      <div class="info-label"><span>🎯 Vaga</span></div>
      <div class="info-value">Entregador</div>

      <div class="info-label"><span>⏰ Turno e Horário</span></div>
      <div class="info-value">Noturno - 6h</div>

      <a href="#" class="details-button">Detalhes ›</a>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <img src="{% static 'core/img/Nike.jpg' %}">
    </div>
    <div class="card-body">
      <p class="company-name">Nike<span class="status">Ativa</span></p>
      <p class="company-location">Natal/RN</p>

      <div class="info-label"><span>🎯 Vaga</span></div>
      <div class="info-value">Atendente de loja</div>

      <div class="info-label"><span>⏰ Turno e Horário</span></div>
      <div class="info-value">Integral - 6h</div>

      <a href="#" class="details-button">Detalhes ›</a>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <img src="{% static 'core/img/Brisanet.png' %}">
    </div>
    <div class="card-body">
      <p class="company-name">Brisanet<span class="status">Ativa</span></p>
      <p class="company-location">Pau dos Ferros/RN</p>

      <div class="info-label"><span>🎯 Vaga</span></div>
      <div class="info-value">Operador de Suporte</div>

      <div class="info-label"><span>⏰ Turno e Horário</span></div>
      <div class="info-value">Noturno - 6h</div>

      <a href="#" class="details-button">Detalhes ›</a>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <img src="{% static 'core/img/Nubank.jpg' %}">
    </div>
    <div class="card-body">
      <p class="company-name">Nubank<span class="status">Ativa</span></p>
      <p class="company-location">Rio de Janeiro/RJ</p>

      <div class="info-label"><span>🎯 Vaga</span></div>
      <div class="info-value">Front-End</div>

      <div class="info-label"><span>⏰ Turno e Horário</span></div>
      <div class="info-value">Integral - 6h</div>

      <a href="#" class="details-button">Detalhes ›</a>
    </div>
  </div>

</div>
</section>


</body>
</html>
{% endblock %}

candidato/templates/candidato/tela_principal_candidato.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}WorkConnect | Início{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'candidato/css/tela_principal_candidato.css' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
</head>
<body>

<header class="navbar">
<div class="container">
<img src="{% static 'core/img/LogoTemplate.png' %}" alt="WorkConnect" class="logo">
<nav>
<a href="#">Plataforma</a>
<a href="#">Serviços</a>
<a href="#">Suporte</a>
</nav>
<div class="user-icon">
<i class="fa-solid fa-bell"></i>
</div>
</div>
</header>

<section class="hero">
<div class="hero-content">
<div class="text">
<h1>Encontre um emprego



que seja adequado aos seus interesses e habilidades.</h1>
<p>Aqui você encontra as melhores opções.</p>

    <div class="search-bar">
      <input type="text" placeholder="Cargo, palavra-chave..." class="input-job">
      <input type="text" placeholder="Sua localização" class="input-location">
      <button>Buscar Vaga</button>
    </div>
  </div>
  <img src="{% static 'core/img/Dashboard.png' %}" alt="Pessoa trabalhando" class="hero-img">
</div>


</section>

<section class="stats">
<div class="stats-container">
<div class="stat">
<div class="icon"><i class="fa-solid fa-briefcase"></i></div>
<p class="label">Vagas Disponíveis</p>
<p class="value">234</p>
</div>
<div class="stat">
<div class="icon"><i class="fa-solid fa-file-circle-check"></i></div>
<p class="label">Candidaturas Enviadas</p>
<p class="value">12</p>
</div>
<div class="stat">
<div class="icon"><i class="fa-solid fa-building"></i></div>
<p class="label">Empresas Ativas</p>
<p class="value">189</p>
</div>
</div>
</section>

<section class="vagas-section">
<h2 class="vagas-title">Vagas Recentes</h2>

<div class="vagas-legenda">
<span class="legenda-item">
<span class="bolinha verde"></span> Disponíveis
</span>
<span class="legenda-item">
<span class="bolinha laranja"></span> Estágio
</span>
</div>

<div class="cards-container">

<div class="card">
<div class="card-header">
<img src="{% static 'candidato/img/Ellipse 14.png' %}">
</div>
<div class="card-body">
<p class="company-name">Elétrica Cervejaria <span class="status">Ativa</span></p>
<p class="company-location">Pau dos Ferros/RN</p>

  <div class="info-label"><span>🎯 Vaga</span></div>
  <div class="info-value">Barmen</div>

  <div class="info-label"><span>⏰ Turno e Horário</span></div>
  <div class="info-value">Noturno - 4h</div>

  <a href="#" class="details-button">Detalhes ›</a>
</div>


</div>

<div class="card">
<div class="card-header">
<img src="{% static 'candidato/img/Farmacia.png' %}">
</div>
<div class="card-body">
<p class="company-name">Farmacia Ideal <span class="status">Ativa</span></p>
<p class="company-location">Pau dos Ferros/RN</p>
<div class="info-label"><span>🎯 Vaga</span></div>
<div class="info-value">Farmacêutico</div>
<div class="info-label"><span>⏰ Turno e Horário</span></div>
<div class="info-value">Integral - 10h</div>
<a href="#" class="details-button">Detalhes ›</a>
</div>
</div>

<div class="card">
<div class="card-header">
<img src="{% static 'candidato/img/Hotel.png' %}">
</div>
<div class="card-body">
<p class="company-name">West Hotel <span class="status">Ativa</span></p>
<p class="company-location">Pau dos Ferros/RN</p>
<div class="info-label"><span>🎯 Vaga</span></div>
<div class="info-value">Camareiro (a)</div>
<div class="info-label"><span>⏰ Turno e Horário</span></div>
<div class="info-value">Meio périodo - 6h</div>
<a href="#" class="details-button">Detalhes ›</a>
</div>
</div>

<div class="card">
<div class="card-header">
<img src="{% static 'candidato/img/Peechinchou.png' %}">
</div>
<div class="card-body">
<p class="company-name">Pechinchou <span class="status">Ativa</span></p>
<p class="company-location">Pau dos Ferros/RN</p>

  <div class="info-label"><span>🎯 Vaga</span></div>
  <div class="info-value">Social Media</div>

  <div class="info-label"><span>⏰ Turno e Horário</span></div>
  <div class="info-value">Fléxivel - 8h</div>

  <a href="#" class="details-button">Detalhes ›</a>
</div>


</div>

<div class="card">
<div class="card-header">
<img src="{% static 'candidato/img/Atacarejo.png' %}">
</div>
<div class="card-body">
<p class="company-name">Nosso Atacarejo <span class="status">Ativa</span></p>
<p class="company-location">Pau dos Ferros/RN</p>

  <div class="info-label"><span>🎯 Vaga</span></div>
  <div class="info-value">Operador(a) de caixa</div>

  <div class="info-label"><span>⏰ Turno e Horário</span></div>
  <div class="info-value">Integral - 8h</div>

  <a href="#" class="details-button">Detalhes ›</a>
</div>


</div>

<div class="card">
<div class="card-header">
<img src="{% static 'candidato/img/Pizzaria.png' %}">
</div>
<div class="card-body">
<p class="company-name">Água na boca<span class="status">Ativa</span></p>
<p class="company-location">Pau dos Ferros/RN</p>

  <div class="info-label"><span>🎯 Vaga</span></div>
  <div class="info-value">Entregador</div>

  <div class="info-label"><span>⏰ Turno e Horário</span></div>
  <div class="info-value">Noturno - 6h</div>

  <a href="#" class="details-button">Detalhes ›</a>
</div>


</div>

<div class="card">
<div class="card-header">
<img src="{% static 'candidato/img/Nike.jpg' %}">
</div>
<div class="card-body">
<p class="company-name">Nike<span class="status">Ativa</span></p>
<p class="company-location">Natal/RN</p>

  <div class="info-label"><span>🎯 Vaga</span></div>
  <div class="info-value">Atendente de loja</div>

  <div class="info-label"><span>⏰ Turno e Horário</span></div>
  <div class="info-value">Integral - 6h</div>

  <a href="#" class="details-button">Detalhes ›</a>
</div>


</div>

<div class="card">
<div class="card-header">
<img src="{% static 'candidato/img/Brisanet.png' %}">
</div>
<div class="card-body">
<p class="company-name">Brisanet<span class="status">Ativa</span></p>
<p class="company-location">Pau dos Ferros/RN</p>

  <div class="info-label"><span>🎯 Vaga</span></div>
  <div class="info-value">Operador de Suporte</div>

  <div class="info-label"><span>⏰ Turno e Horário</span></div>
  <div class="info-value">Noturno - 6h</div>

  <a href="#" class="details-button">Detalhes ›</a>
</div>


</div>

<div class="card">
<div class="card-header">
<img src="{% static 'candidato/img/Nubank.jpg' %}">
</div>
<div class="card-body">
<p class="company-name">Nubank<span class="status">Ativa</span></p>
<p class="company-location">Rio de Janeiro/RJ</p>

  <div class="info-label"><span>🎯 Vaga</span></div>
  <div class="info-value">Front-End</div>

  <div class="info-label"><span>⏰ Turno e Horário</span></div>
  <div class="info-value">Integral - 6h</div>

  <a href="#" class="details-button">Detalhes ›</a>
</div>


</div>

</div>
<div class="ver-mais-container">
<button class="ver-mais-btn">Ver mais</button>
</div>
</body>
</html>
{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WorkConnect - Dashboard Candidato</title>

    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="sidebar">
        <div class="profile-header"> 
            <img src="{% static 'core/img/cristiano.jpg' %}" alt="Usuário">
            <h6>Olá, {{ request.user.first_name|default:"Cristiano" }}!</h6>
        </div>
        <hr>

        <a href="{% url 'candidato:tela_principal_candidato' %}" class="active"><i class="fa-solid fa-house"></i> Início</a>
        <a href="{% url 'candidato:perfil_candidato' %}"><i class="fa-solid fa-user"></i> Perfil</a>
        <a href="{% url 'candidato:candidaturas_candidato' %}"><i class="fa-solid fa-briefcase"></i> Candidaturas</a>
        <a href="{% url 'candidato:vagas_candidato' %}"><i class="fa-solid fa-building"></i> Vagas</a>
        <a href="#"><i class="fa-solid fa-right-from-bracket"></i> Sair</a>
    </div>

    <div class="main-wrapper"> 
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="footer">
            <div class="footer-content">
                <div class="footer-left">
                    <img src="{% static 'core/img/Logo_WorkConnect.png' %}" alt="WorkConnect Logo" class="footer-logo">
                    <p class="footer-text">
                        WorkConnect, uma plataforma para facilitar a divulgação e a busca por vagas de emprego, focado no comércio local
                    </p>
                    <div class="footer-icons">
                        <a href="#"><i class="fa-brands fa-instagram"></i></a>
                        <a href="#"><i class="fa-brands fa-facebook"></i></a>
                        <a href="#"><i class="fa-brands fa-github"></i></a>
                    </div>
                </div>

                <div class="footer-section">
                    <h4>Plataforma</h4>
                    <ul>
                        <li><a href="#">Sobre nós</a></li>
                        <li><a href="#">Serviços</a></li>
                        <li><a href="#">Testemunhos</a></li>
                    </ul>
                </div>

                <div class="footer-section">
                    <h4>Contatos</h4>
                    <ul>
                        <li><a href="#">Email</a></li>
                        <li><a href="#">Telefone</a></li>
                        <li><a href="#">Discord</a></li>
                    </ul>
                </div>
            </div>

            <hr>

            <div class="footer-bottom">
                <p>&copy; Copyright 2025 Work Connect</p>
            </div>
        </footer>
    </div>
    </body>
</html>